### ISSUE TITLE
title + subtitle in the <header> section

### ISSUE THREAD

**Issue by fabi1cazenave** [Nuclear-Squid/ergol#130]
The subtitle is currently in the `<main>` container, whereas the title is in the `<header>`. This is not optimal, and both should be defined in the document metadata rather than in the markdown/html content.

**Comment by Nuclear-Squid** [comment]
What are you calling the « subtitle » ? My guess is the page title (like «Ergo‑L ou Bépo ? » in the [bépo page](https://ergol.org/bepo/)), but it *is* in the header.

**Comment by fabi1cazenave** [comment]
That page is not concerned, but other pages are affected : 

![image](https://github.com/Nuclear-Squid/ergol/assets/457778/cafde563-71fa-4e7c-befb-6baee644f534)

**Comment by fabi1cazenave** [comment]
Fixed by #142 : the title is now in the `<main>` container, and the `<nav>` container is betweet `<header>` and `<main>`.
