### ISSUE TITLE
Fournir le fichier xkb complet dans la release

### ISSUE THREAD

**Issue by lord-re** [Nuclear-Squid/ergol#175]
La page release propose pleins de fichiers pour le layout.
Pour linux, ce n'est que le fichier symbol qui est fourni et non le layout complet.
Étant utilisateur de sway, il lui faut le layout complet pour que ça passe.

Kalamine sort les deux fichiers mais pour éviter de devoir utiliser kalamine, ça pourrait être sympa de distribuer le fichier.

Ha et d'ailleurs en passant : sur le site ouaib, les liens de téléchargement ressemblent plus à des titres de section qu'à des liens de téléchargement… Ptet mettre une icone ou souligner ou autre ?

**Comment by Nuclear-Squid** [comment]
Pour les fichiers xkb complets, je suis pas totalement sûr que ça soit une super idée parce que ça écraserait les autres dispos de la locale `fr` qu’on aurait installé. Kalamine sait faire l’install dans la locale fr par contre, donc ça risque d’être une meilleur solution pour installer ergol de façon propre.

(Bon, avec un peut de chances, on aura bientôt même plus besoin d’installer ergol à la main sous linux ^^ https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/690)

Ah et bien vu pour les liens de la page d’install, faudra que je corrige ça quand j’aurai un bout de temps.

**Comment by lord-re** [comment]
Dans mon cas je le charge manuellement dans sway.
En gros je dis à sway 

  > input type:keyboard {
  xkb_file /home/lord/.config/xkb/ergol.xkb
}

Donc ça n'écrase rien. C'est pas installé proprement mais en attendant l'inclusion dans xkb ça permet de le faire simplement (même sans droit root).

**Comment by fabi1cazenave** [comment]
Oups, j’arrive tard, mais est-ce que le pilote `xkb_symbols` ne suffit pas ?

https://github.com/Nuclear-Squid/ergol/releases/download/ergol-v1.0.0/ergol.xkb_symbols

**Comment by lord-re** [comment]
Hoo bha maintenant que c'est arrivé dans xkb, plus besoin de s'embêter :-) 

input type:keyboard {
  xkb_layout fr,fr,fr,us
  xkb_variant ergol,bepo,,
}

Ça permet d'avoir ergol,bépo,azerty et qwerty à portée de doigts.
