### ISSUE TITLE
articles - afficher le nom de l’auteurice en haut

### ISSUE THREAD

**Issue by B0pol** [Nuclear-Squid/ergol#205]
Ne pas mettre le nom de l’auteurice en haut rend le contenu plus "officiel", alors que pourtant l’article peut être personnel

exemple ici:
![image](https://github.com/user-attachments/assets/63512fdc-4677-473d-9227-c11c9952d259)
qui a changé **neuf fois** de disposition de clavier ??? Ergo-L ??? On ne le saura qu’en bas de la page 😆 

Je pense que juste à côté de la date est une bonne place. D’ailleurs c’est ce que font la plupart des sites de presse (qui sont pourtant ultra impersonnels ~~sauf certains hum hum~~) et des blogs (plus personnels).
Et par conséquent plus besoin d’indiquer le nom de l’auteurice en bas de la page.

**Comment by Nuclear-Squid** [comment]
Je prends *enfin* le temps de regarder ton issue, ça joue ça niveau présentation ?
![Screenshot 2024-09-13 at 19-05-04 Apprendre une disposition de clavier Ergo‑L](https://github.com/user-attachments/assets/fce02c02-c0aa-4e6d-b43f-e8a209edf5b3)

**Comment by fabi1cazenave** [comment]
fixed by #259
