### ISSUE TITLE
La touche Q d'un clavier azerty ne correspond pas à la touche A dans Duck typist

### ISSUE THREAD

**Issue by badmrfrosty** [Nuclear-Squid/ergol#208]
Bonjour,

Je tente d'apprendre la disposition de clavier Ergo-L avec l'outil Duck Typist proposé sur le site. Cela fonctionne pour toutes les lettres qui sont à une place identique en azerty qu'en qwerty. Par contre, pour le A, W, M, etc., il y a une incohérence entre les dispositions:

Lorsque j'appuie sur la touche Q en azerty, ce n'est pas la touche A qui s'illumine dans Duck Typist mais la touche Q. Pareil lorsque je presse la touche M en azerty, c'est la touche H qui s'illumine dans Duck Typist au lieu de la touche U. 

En dehors de cela, firefox fonctionne bien en azerty, pareil pour le reste du gestionnaire de fenêtres.

Je suis sous Linux, i3 comme gestionnaire de fenêtres et juste cette ligne dans .xprofile concernant la disposition clavier:

`# Switch to BE with Caps as Mod/Escape
setxkbmap -option caps:super -layout be && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
`

Quelqu'un a une piste pour expliquer ce comportement?

Merci d'avance,

**Comment by Nuclear-Squid** [comment]
Bonjour ! Désolé de te faire attendre aussi longtemps pour te répondre.

Je viens de faire quelques tests, et je pense que le problème viens du navigateur. [X-keyboard](https://github.com/OneDeadKey/x-keyboard), le web component qu’on utilise pour afficher et émuler les dispositions de clavier utilise l’API navigateur keyboard (voir [ici](https://github.com/OneDeadKey/x-keyboard/blob/6fd0c9f9276cbb08061560a5d3ec543660815cc2/src/x-keyboard.js#L158-L191)), et l’event keyDown est sensé donner la touche physique du clavier dans la propriété [keyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) (ce qui n’es visiblement pas le cas chez toi).

Pourrais-tu me donner plus d’informations sur ton navigateur ? Numéro de version, extensions, paramètres du navigateur, options pour résister au fingerprinting… perso j’ai le bug dans librewolf (un fork de firefox) v128.0, mais pas dans firefox v128.0.3.

Je suspecte que la resistance au fingerprinting en soit la cause, mais j’en suis pas sûr du tout.

(En attendant, tu peux essayer de passer sur Qwerty pour DuckTypist, où installer Ergo‑L et t’entraîner sur [Keybr](https://www.keybr.com/), c’est pas ouf comme compromis, mais au moins tu peux continuer de t’entraîner…)

**Comment by Nuclear-Squid** [comment]
C’est bien ça, désactiver `privacy.resistFingerprinting` dans about:config dans Librewolf corrige le problème (et à l’inverse, l’activer dans Firefox le réintroduit). Est-ce que ça corrige le problème chez toi ?

**Comment by badmrfrosty** [comment]
Bonsoir,

Effectivement, désactiver le fingerprinting fonctionne pour moi également. 

Jusqu'à présent, je m'entraînais dans une VM openBSD ...

Un grand merci,
