### ISSUE TITLE
Website : add a section users’ reviews

### ISSUE THREAD

**Issue by apraga** [Nuclear-Squid/ergol#218]
Une idée suggérée par [Taskwarrior](https://taskwarrior.org/docs/workflow/). L’objectif est de motiver les gens en listant des avis.

1. Une section avec des liens externes [comme celui-ci](https://geobert.fr/posts/l-apres-bepo-ergo-l/). Cela permettrait aussi d’augmenter la visibilité de ces blogs.
2. Une section "interne" avec des avis des utilisateurs ( point de départ sur le discord [ergol vs bepo pour exemple](https://discord.com/channels/1046720208171175946/1198201037593518115/1267861575742652437) )

Pour avis. Merci !

**Comment by Nuclear-Squid** [comment]
Oops, j’ai pas vu qu’il y avait cette issue quand on a bossé sur #232. Je vais fermer ça à la main du coup. Désolé pour le silence sur la question, mais merci pour la suggestion !
