### ISSUE TITLE
Incomplete readme

### ISSUE THREAD

**Issue by DoomDuck** [Nuclear-Squid/ergol#23]
Hello, I was told that Kalamine needs to be installed as root to work.
However this is not specified in the readme guide.

**Comment by Nuclear-Squid** [comment]
Hi ! Sorry for not addressing this issue sooner, I will add more detailed instructions as part of the release of the next version of Ergo-L. You can expect a pull request this evening (or early tomorrow), it will be opened to review by anyone to make sure I didn’t miss anything ^^
