### ISSUE TITLE
La double touche morte pour les caractères avec tréma (ä, ë, ö, ü, ÿ) ne fonctionne pas

### ISSUE THREAD

**Issue by artav4** [Nuclear-Squid/ergol#244]
Bonjour,

Je suis sous Arch Linux, sous KDE Plasma Wayland. avec Ergo-L en tant que disposition par défaut, la touche morte fonctionne correctement mais je ne peux pas accéder aux caractères avec tréma qui sont sous la double touche morte, en appuyant deux fois sur cette dernière, c'est comme si je n'avais appuyé sur aucune touche au préalable. Savez-vous d'où cela peut venir ?

Maj : on dirait que le problème est exclusif à Wayland

**Comment by fnuttens** [comment]
@artav4 J’ai eu le même problème cet été sur KDE Plasma 6.1, le tréma fonctionnait sur l’écran de login donc c’était lié à un bug du DE. Malheureusement la seule solution pour moi fut de passer à Gnome.

**Comment by artav4** [comment]
Merci pour ta réponse ! Je vais en discuter sur le discord

**Comment by artav4** [comment]
Résolu avec KDE Plasma 6.2
