### ISSUE TITLE
Learn page is broken

### ISSUE THREAD

**Issue by AntoineD** [Nuclear-Squid/ergol#289]
Hello, the learn page no longer shows the words to type: https://ergol.org/dactylo/

**Comment by vpicavet** [comment]
Confirmed on firefox and chromium.

**Comment by pierre-eliep-met** [comment]
it works after clicking many times on the duck !

**Comment by shinze** [comment]
Clicked the ducks :) and reloaded the page but still have an error in the console (Firefox Latest).
<img width="964" alt="image" src="https://github.com/user-attachments/assets/780df961-ff45-4424-b698-d178f8594c17">

**Comment by Nuclear-Squid** [comment]
I just fixed it, I forgot to revert an extra commit. Sorry about that

**Comment by pierre-eliep-met** [comment]
Thanks, it's all good now !
