### ISSUE TITLE
Échanger les touches `-` et `.`

### ISSUE THREAD

**Issue by pierre-eliep-met** [Nuclear-Squid/ergol#293]
Bonjour bonjour, déjà merci beaucoup pour tout ce travail, c’est super !

Je trouve qu’accéder au `.` n’est pas le plus agréable (le suis sur un clavier type matrix 2030), contrairement au `-` qui est très accessible.
D’après le wiki [bépo](https://bepo.fr/wiki/Fr%C3%A9quence_des_caract%C3%A8res), sur les trois corpus utilisés, le `-` est moins utilisé que le `.`, ça me semblerait pertinent de les échanger, sans échanger les symboles en alt-gr sur ces touches pour garder les `[]`

Qu’en pensez-vous ? :)

**Comment by Nuclear-Squid** [comment]
Hello ! On compte pas changer la dispo, vu que le travail de développement est terminé et que changer la dispo maintenant serait trop compliqué (vu qu’il faudrait envoyer les modifs sur XKB, et donc imposer le changement à tous ceux qui ont déjà installé la dispo)

Après, pour ce qui est de ta proposition, oui le `.` est plus fréquent que le `-`, mais c’est un peu pour ça qu’on les places comme ça : le majeur gauche est déjà trop chargé, et la seule raison pour laquelle ça reste confortable c’est qu’il n’y a pratiquement pas de bigrammes de même doigts dessus. Échanger le `.` et `-` rajouterai de la charge et des bigrammes de même doigts sur un doigts qui travaille déjà trop ,ce qui serait pas super.

(Hésite pas à rejoindre notre serveur discord si l’ergonomie clavier t’intéresse !)

**Comment by pierre-eliep-met** [comment]
Ah oui j'avais pas pensé à la charge du majeur, ni à toute la suite avec xkb. 
Je n'ai pas discord pour le moment, mais je garde en tête si jamais merci ! :) (après j'essaie de limiter mon obsession sur le sujet 😇)
