### ISSUE TITLE
Échanger `’` et `-` pour avoir l’apostrophe en accès direct

### ISSUE THREAD

**Issue by pierre-eliep-met** [Nuclear-Squid/ergol#294]
Bonjour bonjour, encore merci beaucoup pour tout ce travail, seconde issue en 2 minutes 😇

Je trouve qu’accéder au `’` n’est pas le plus agréable surtout que l’apostrophe est souvent suivie d’un `é`, qui réutilise la touche morte.
D’après le wiki [bépo](https://bepo.fr/wiki/Fr%C3%A9quence_des_caract%C3%A8res), encore lui, sur les trois corpus utilisés, le `-` est moins utilisé que le `’`, et je trouve ça tout aussi pertinent d’avoir un tiret en touche morte sur l’espace qu’une apostrophe.

J’entends le besoin du `-` pour la programmation, mais le `’` est également utile en anglais, plus que le `-` (full feeling au doigt mouillé), et le `-` est également sur la couche de symbole à côté du `+` comme on s’y attend

Qu’en pensez-vous ? :)

**Comment by Nuclear-Squid** [comment]
Hello ! Comme je disais dans #293 on va pas changer des trucs dans la dispo, mais je vais quand même expliquer notre choix ^^

Mettre le `’` sous le `e` donnerai les mêmes problèmes que ceux cités dans #293 (avec le `.`) mais en pire, vu que l’apostrophe est encore plus fréquente et s’enchaîne encore plus dans le `e` et `o`.

Finalement, l’apostrophe est relativement fréquente par rapport aux autres ponctuations, et s’enchaîne pas pas mal de lettres fréquentes. L’avoir derrière la touche morte ça permet de caler cette touche au dessus du `i` pour limiter les bigrammes de même doigts (bon sauf pour `I’m` en anglais, mais ça va c’est pas trop fréquent). On a essayé de garder le `’` en accès direct, mais ça marchait pas super pour Ergo‑L.

Après, on se pose la question pour d’autres de nos dispos, par exemple avoir l’apostrophe en direct risque de mieux marcher pour Erglace, et on y réfléchis en ce moment.

**Comment by pierre-eliep-met** [comment]
Ok, merci pour le détail, c'est très clair :)
