### ISSUE TITLE
'xkalamine install ergol.yaml' casse les dispositions de claviers fr dans GNOME

### ISSUE THREAD

**Issue by axelsimon** [Nuclear-Squid/ergol#32]
Bonjour,
Je ne sais pas si c'est un bug dans (x)kalamine ou ergol, dans le doute je commence ici.

Un `sudo xkalamine install ergol.yaml` pète les dispositions de claviers française, dans Fedora 38 avec GNOME 44.5 (et Wayland).

Après installation, la disposition est bien détectée par xkalamine : 
```bash
sudo xkalamine list
fr/ergol                   French (Ergo-L)
```
 mais :
1. Elle n'apparaît pas dans les dispositions séléctionables et
2. Toutes les autres dispositions français, à l'exception de "fr-azerty (m17n)" disparaissent des dispositions disponibles

![image](https://github.com/Nuclear-Squid/ergol/assets/1172256/9b4022cd-9dda-4e49-a903-2b1bc788ee77)

Tenter de basculer vers Ergol en utilisant le conseil de Kalamine:
`setxkbmap fr -variant ergol` crée des résultats suprenants, avec par exemple Thunderbird ou Joplin qui utilisent ErgoL mais Firefox ou Element non.

Pour comparaison, après un `sudo xkalamine remove fr/ergol` :
![image](https://github.com/Nuclear-Squid/ergol/assets/1172256/c0d76544-0769-4a98-9d63-f760326e9fd5)

Beaucoup moins drôle, si on laisse en l'état, après un redémarrage, la disposition de clavier utilisée dans mon cas (bépo) n'est plus utilisable dans GDM (mais l'est dans un vTTY). Le Qwerty fonctionnait toujours, mais aucune idée si c'est parce qu'il est configuré en tant que disposition secondaire ou non…

**Comment by hobbes** [comment]
commentaire ajouté dans le bug xkalamine, que je reproduis ici: 

j'ai des messages dans journald:

```
nov 02 14:58:29 sphax systemd[3026]: Started app-gnome-gnome\x2dkeyboard\x2dpanel-470511.scope - Application launched by gnome-shell.
nov 02 14:58:29 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: No declaration for attribute type of element variant
nov 02 14:58:29 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: XML error: failed to validate document at /usr/share/X11/xkb/rules/evdev.xml
nov 02 14:58:29 sphax gnome-control-c[470511]: Failed to load 'evdev' XKB layouts
nov 02 14:58:29 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: No declaration for attribute type of element variant
nov 02 14:58:29 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: XML error: failed to validate document at /usr/share/X11/xkb/rules/evdev.xml
nov 02 14:58:29 sphax gnome-control-c[470511]: Failed to load 'evdev' XKB layouts
nov 02 14:58:29 sphax gnome-shell[3312]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
nov 02 14:58:33 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: No declaration for attribute type of element variant
nov 02 14:58:33 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: XML error: failed to validate document at /usr/share/X11/xkb/rules/evdev.xml
nov 02 14:58:33 sphax gnome-control-c[470511]: Failed to load 'evdev' XKB layouts
nov 02 14:58:33 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: No declaration for attribute type of element variant
nov 02 14:58:33 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: XML error: failed to validate document at /usr/share/X11/xkb/rules/evdev.xml
nov 02 14:58:33 sphax gnome-control-c[470511]: Failed to load 'evdev' XKB layouts
nov 02 14:58:33 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: No declaration for attribute type of element variant
nov 02 14:58:33 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: XML error: failed to validate document at /usr/share/X11/xkb/rules/evdev.xml
nov 02 14:58:33 sphax gnome-control-c[470511]: Failed to load 'evdev' XKB layouts
nov 02 14:58:33 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: No declaration for attribute type of element variant
nov 02 14:58:33 sphax gnome-keyboard-panel.desktop[470511]: xkbregistry: ERROR: XML error: failed to validate document at /usr/share/X11/xkb/rules/evdev.xml
nov 02 14:58:33 sphax gnome-control-c[470511]: Failed to load 'evdev' XKB layouts
```

ergol installé via xkalamine (sudo xkalamine install ergol.yaml) puis j'ouvre la configuration de claviers de gnome. Toutes les dispositions ont disparu, pas seulement le Français.

**Comment by Nuclear-Squid** [comment]
Hello ! J’ai vu que t’as laissé le même commentaire dans l’issue sur le répo de Kalamine (avant le fix de Kazé). Est-ce que le problème est résolu ?

**Comment by fabi1cazenave** [comment]
Le bug a été corrigé depuis quelque temps déjà coté Kalamine. Désolé du désagrément !
