### ISSUE TITLE
Link to stats in readme is broken

### ISSUE THREAD

**Issue by sephii** [Nuclear-Squid/ergol#36]
The link to stats in the README is broken:

> […] to benchmark layouts on the [stats page](https://github.com/Nuclear-Squid/ergol/blob/master/ergol.org/stats).

**Comment by Nuclear-Squid** [comment]
Thanks for pointing that out ! I checked the other links on readme and the website itself and found a few other broken links (another stats page link in the readme and an old discord link on the page itself).

I’ll fix that right away
