### ISSUE TITLE
Avoir une version « frappe en A » pour clavier ISO

### ISSUE THREAD

**Issue by nemolivier** [Nuclear-Squid/ergol#50]
La touche <> du clavier ISO contient des caractères redondants, mais occupe une place très ergonomique quand on frappe en dactylo sur un clavier ISO, avec la méthode « en A ».
Je propose de décaler les touches de la rangée du bas de la main gauche d'une case vers la gauche. La touche libérée (qui porte le B à l'heure actuelle) pourrait porter une autre redondance plus pratique : un autre AltGr ou une redondance de la touche modificatrice. Ou tout autre chose.

**Comment by Nuclear-Squid** [comment]
Hello ! Je préfère pas implémenter le angle mod (ou « méthode en A », comme tu dis) dans la dispo, en grande partie parce que c’est une préférence personnelle qui devient vite compliqué : Quelle touche on met au centre, sur B ? Perso j’ai laissé la touche <> pour m’en faire un leader de compose, mais on peut carrément vouloir tab, entrée, backspace, echap… Ça fait déja 5 pilotes  en plus si on veut prendre toutes ces possibilités.

J’avais discuté de ça avec l’auteur de Kalamine, (l’outil qui génère les pilote), et on pense rajouter une option `--angle-mod <touche>`, qui permettrai de builder une dispo en angle mod avec `<touche>` à  la place du B, comme ça chacun choisi quelle touche y mettre. Je vais ouvrir une issue côté Kalamine, pour y faire une demande un peu plus formelle.

En attendant, tu peux utiliser `kanata`, pour implémenter des fonctionnalités qmk sur n’importe-quel clavier, y compris remapper les touches (et donc implémenter l’angle mod comme tu veux). Sur le serveur discord d’Ergo‑L on développe aussi le projet [Arsenik](https://github.com/OneDeadKey/arsenik/tree/main), une config kanata (et plus tard keyd, kmonad, qmk…) qui cherche à guider les néophytes dans leur exploration des capacités de leurs clavier 🙃.

Arsenik a dans la section `mods` un morceau de config pour implémenter l’angle-mod, et c’est ce que j’utilise. Ça a l’avantage d’implémenter beaucoup plus de choses que juste l’angle mod (comme des home‑row mods, par exemple), et de permettre de lancer des configs différentes suivant le clavier (donc tu peux avoir une config avec angle-mod sur ton clavier iso, mais ne pas l’activer sur ton clavier externe ortho-linéaire par exemple).

J’espère que tout ça arrive à t’aider !

**Comment by lobre** [comment]
Je ne sais pas s'il faut fermer cette issue de suite. J'étais de ton avis @Nuclear-Squid, pour moi pas trop de sens de s'encombrer avec plusieurs version différentes de la dispo en fonction de angle mod ou non.

Mais j'aurais tendance à dire qu'il faudrait jouer un peu plus longtemps avec ce mod avant de statuer. Bien sûr, c'est implémentable plus haut via un tool comme kanata. Mais ça demande un peu plus de boulot, ainsi que des permissions pour le setup.

Je me demande si ça ne ferait pas de sens de juste publier deux dispos. Une simple, et une angle mod. La touche `<>` passerait sur `[b]`, pas besoin d'anticiper ou de mapper quelque chose de spécifique. Ou on le force de manière très opinioné à quelque chose comme "backspace" (je ne sais pas ce que font les autres dispo angle mod?). Et l'utilisateur pourra remaper toute manière si vraiment nécessaire.

À méditer. J'arrive pour le moment pas à savoir si fest une bonne idée ou pas. Il faut que je joue davantage avec l'angle mod. Mais si le confort est vraiment bon, ça permettrait de le rendre accessible au plus grand nombre (sans viser uniquement les geeks qui remap tout via qqch comme kanata).

**Comment by Nuclear-Squid** [comment]
Je vais garder cette issue ouverte encore un peu, parce que ça permet de garder cette discussion au même endroit.

Je pense préférer laisser les gens bidouiller leur dispo avec Kalamine. Si il faut juste installer Kalamine et le lancer avec la bonne option, je pense que ça devrait pas être trop compliqué. Kalamine sais générer les pilotes « mobiles », ceux qu’on peut lancer sans rien installer (comme les pilotes ahk sous windows), donc *pire des cas*, on peut générer les pilotes à la maison et les utilises sur un poste où on a pas les droits d’admin. Ça serait encore plus simple si @fabi1cazenave arrive a faire tourner Kalamine dans une page web, mais il faudrait peut‑être attendre un peu, voir comment le projet évolue avant de pouvoir prendre une décision définitive.

**Comment by lobre** [comment]
Il y a un point aussi que je viens de relever, c’est que dans le cas où l’on parle d’un laptop avec clavier ISO, si on  veut également de temps en temps brancher un clavier externe programmable, ça veut dire qu’il faudra switch entre la version angle mod et non angle mod de la dispo OS. Ou bien programmer son clavier avec l’angle mod en tête. C’est pas terrible sur ce cas d’utilisation. Un point du côté de kanata/keyd pour ça.

**Comment by nemolivier** [comment]
Merci pour les réponses. Il n'y a pas de « bonne » manière, à mon sens. Ce serait plutôt un « choix éditorial », de plus ou moins pousser cet angle mod. Pour ma part je trouve que c'est une solution ultra-élégante pour utiliser un clavier de portable en évitant de trop « casser » le poignet droit. Mais j'avais beau essayer de pousser cette variante pour le bépo, je n'ai jamais eu gain de cause ! Bon, à l'époque, on n'avait pas cette option dans les pilotes…
Il faudrait que je trouve le temps de me pencher sur toutes ces nouvelles solutions, je suis bloqué sous Windows à cause du travail, j'utilise une vieille version de pkl pour avoir ma version perso du bépo sous les doigts…

**Comment by lobre** [comment]
> ça peut créer de la confusion pour les utilisateurs qui installeront Ergo‑L sur leur laptop ISO et qui s’attendent à ce que leur clavier ortholinéaire favori se comporte de la même façon…

C’est un point que je voulais remonter également. Peut-être qu’il justifie le fait que la dispo OS ne soit pas le meilleur endroit pour héberger l’angle mod. Où alors, c’est pour les utilisateurs initiés qui sauront le manipuler, adapter leur clavier externe, ou changer de dispo OS au besoin.

Mais tu résumes bien les étapes !

**Comment by fabi1cazenave** [comment]
https://github.com/OneDeadKey/kalamine/pull/91

**Comment by Ced-C** [comment]
Avoir la dispo installée en classique **et** en variante A, ça me semble la façon la plus simple de switcher entre les deux.

Quasiment tous les bureaux le permette de façon simple sans ouvrir les paramètres.

Après oui, ça fait faire un plus grand nombre de pilote, mais avec kalamine ça n’est pas bien dur à faire (d’autant que je viens de faire une implèm’ basique d’un tag --angle-mod).

Le seul truc qui me fait douter, c’est que la variante A sur Bépolar, Erglace, Optimot, pourquoi pas. Mais j’ai l’impression qu’avec Ergo-L, on pert l’intéret d’avoir préservé les raccourcis clavier Ctrl Z X V.

**Comment by fabi1cazenave** [comment]
Même s’ils ne correspondent plus à ce qui est écrit sur le clavier, ça reste sympa de pouvoir faire Ctrl-ZXCV d’une seule main. Mais oui, ça ne conviendra pas à tout le monde — et à titre perso je pense qu’il faut que ça reste une option et non un pilote par défaut.

**Comment by fabi1cazenave** [comment]
FWIW, je viens de publier kalamine v0.26 qui supporte cet angle-mod grâce au patch de @Ced-C.

Ça ne permet pas encore de mettre Bacspace en [B], mais c’est de toute façon une option qui rendrait la touche AltGr obligatoire pour saisir les chevrons (`<>`), donc pas nécessairement souhaitable pour Ergo‑L.

**Comment by Nuclear-Squid** [comment]
Je pense qu’on a à peu près fait le tour de la question, mais je pense qu’il faut qu’on réfléchisse à comment distribuer ces pilotes avec angle-mod. Pour moi il y a deux choix : les fournir sur le site ou laisser les gens se débrouiller avec Kalamine. À mon avis, il faut surtout se demander quelle est l’option qui est le plus simple pour les gens non expérimentés, les bons sauront quick switcher entre les deux pilotes, et sauront installer Kalamine.

Je suis tenté de dire que fournir les pilotes en angle-mod sur le site serait le plus simple, mais ça risque de ne pas être la solution la plus élégante. J’aimerai bien votre avis sur ça.

**Comment by lobre** [comment]
C'est cool que la feature soit dispo dans kalamine déjà.

Pour la distribution, ça va aussi pas mal dépendre de comment la version "normale" va être distribuée j'imagine. Donc la question est plus large que la version angle mod.

Perso, je trouve que les releases github sont pas mal pour fournir des artefacts. Et ensuite, bah road to xkb à terme.. Et là, est ce qu'il faudra submit une version angle mod? C'est peut être trop tôt pour répondre à cette question...

**Comment by fabi1cazenave** [comment]
J’ai vu par hasard que Colemak-DH avait une variante angle-mod (ISO) dans XKB. Donc pourquoi pas.

Pour ce qui est de diffuser ces variantes angle-mod sur la page de téléchargement je suis toujours partagé. Parmi les raisons de ne pas le faire :
- beaucoup d’utilisateurs qui réclament l’angle-mod (dont @nemolivier semble-t-il ?) l’utilisent pour changer l’affectation des doigts sur la demi-rangée inférieure basse (e.g. faire le tiret avec l’annulaire plutôt que le majeur), ce qui dénature l’ergonomie de la disposition ;
- ça complique la cohabitation avec un clavier ergonomique externe ;
- c’est source de confusion pour la plupart des utilisateurs.

Donc si on distribue ces pilotes, je crois qu’il faut bien expliquer sur la page de téléchargement de quoi il s’agit, avec un diagramme d’affectation des doigts notamment (comme sur la page colemak-DH).

Et dans tous les cas : oui, il faut diffuser les pilotes dans les releases github, très clairement.

**Comment by lobre** [comment]
> J’ai vu par hasard que Colemak-DH avait une variante angle-mod (ISO) dans XKB. Donc pourquoi pas.

Ah, c’est plutôt une bonne nouvelle, si on part dans cette direction, on est pas les seuls. Et ça veut dire que ça a une chance d’être accepté côté XKB aussi.

> c’est source de confusion pour la plupart des utilisateurs.

> je crois qu’il faut bien expliquer sur la page de téléchargement de quoi il s’agit, avec un diagramme d’affectation des doigts notamment

+1. Je pense qu’en mettant l’accent sur la documentation, on peut réussir à faire passer clairement le message.

> e.g. faire le tiret avec l’annulaire plutôt que le majeur

Pareil pour ça, je savais pas que ça se faisait. Mais si on explique bien le pourquoi du comment, avec des jolis dessins, ça permettra de bien faire passer le message sur le but de ce mod.

**Comment by Nuclear-Squid** [comment]
Je pense que je vais fermer cette issue, car je pense qu’on a fait le tour de la question. Pour Ergo‑L, je pense que je vais (à terme) publier une version angle mod sur le site web. Dans ma [merge request chez xkb-config](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/690), j’ai proposé une version « ISO » en même temps que la version standard, qui met le `backspace` sur [B]. Je pense que c’est une bonne « valeur par défaut » pour la dispo.

Je continue de penser que c’est préférable de laisser les utilisateurs customiser le layout comme bon leur semble (avec Kalamine, Arsenik, QMK…) et mettre l’accent sur la documentation, mais l’angle mod pourrait être particulièrement pratique pour les utilisateurs de pilotes mobiles. Avoir Ergo‑L partout c’est super, mais quand on a l’habitude d’angle mod, ça peut être vraiment déroutant de le perdre d’un coup.

Pour l’instant, je garde juste la version standard du layout sur le site web, mais dès que Kalamine sait générer des layout avec angle-mod je rajouterai une version iso à la page de téléchargements.
