### ISSUE TITLE
[AHK] 1dk+Shift layer is out of sync with 1dk layer

### ISSUE THREAD

**Issue by fnuttens** [Nuclear-Squid/ergol#53]
Hi! I noticed the following issues with version 0.7.0:
- french quotation marks (`« »`) are located on 1dk+shift+[34] instead of 1dk+shift+[23]
- the 1dk+shift layer is out of sync with the 1dk layer: à/Û, é/À, è/É, ê/È, etc.

**Comment by Nuclear-Squid** [comment]
Was supposed to be closed by #52, but didn’t work for some reason.
