### ISSUE TITLE
[dactylo] low contrast for typed letter

### ISSUE THREAD

**Issue by brabalan** [Nuclear-Squid/ergol#60]
Here is what I see after typing the first two words

<img width="982" alt="Screenshot 2024-02-14 at 10 18 09" src="https://github.com/Nuclear-Squid/ergol/assets/1021637/4271d9fb-24fb-40c8-bcb6-62dab2c08f40">

Could the typed letter be more visible (for instance be green)?

**Comment by Nuclear-Squid** [comment]
Hi ! I opened a PR, in case you want to take a look.
