### ISSUE TITLE
Add a lexicon in the statistics page

### ISSUE THREAD

**Issue by Geobert** [Nuclear-Squid/ergol#67]
At the bottom of the page, a lexicon can come helpful

**Comment by Nuclear-Squid** [comment]
Oh that’s a great idea ! I just had an idea though, do you think it’s better to have a lexicon at the end or declare the keywords as abbreviations, with the definition popping up when you hold the cursor over it ? Kind of like the `TL:PL` on [ergol’s main page](https://ergol.org/#optimisation).

**Comment by Geobert** [comment]
The idea is from @fabi1cazenave ^^

**Comment by fabi1cazenave** [comment]
Fixed by #99.
