### ISSUE TITLE
Get Ergo‑L included in xkb-config

### ISSUE THREAD

**Issue by fabi1cazenave** [Nuclear-Squid/ergol#87]
When we reach 1.0 (not before), we should try to get this layout included in xkb. Here’s an example of what should not be done : https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/423

**Comment by Nuclear-Squid** [comment]
I forgot to update this issue, but [it is underway](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/690) ! (Now we wait)

**Comment by gagath** [comment]
@Nuclear-Squid this issue should be closed, the layout was merged :)

**Comment by fabi1cazenave** [comment]
Indeed. Many thanks to @wismill for his work !
